Classic Migration docs
stoplightio/platform-docs pull request #124
Opened 2021-07-02 18:42 UTC by lottamus

- Updates the classic migration docs to include the migration tool
- Adds an article on allowed email domains

2021-07-02 18:55 UTC, marbemac requested changes

2021-07-02 18:55 UTC, marbemac commented on 2.-workspaces/allowed-email-domains.md
> +Allowed email domains let Stoplight know should have automatic access to your Workspace and who needs membership approval.
> let Stoplight know should

"let Stoplight know who should"

2021-07-02 18:55 UTC, marbemac commented on 2.-workspaces/allowed-email-domains.md
> +Now you've configured your company's email domain, you can send your Workspace URL to your teammates, so they can automatically join your Workspace.
> Now you've configured

Now that

---

> to your teammates, so they can automatically

to your teammates and they will be able to automatically...

2021-07-02 18:55 UTC, marbemac commented on 2.-workspaces/allowed-email-domains.md
> +If their email address matches one of your Workspace's allow email domains, Stoplight will add them as a member to your Workspace with the role configured with the email domain.
> configured with the email domain.

configured with the allowed domain.

2021-07-02 18:55 UTC, marbemac commented on 2.-workspaces/allowed-email-domains.md
> +If their email address matches one of your Workspace's allow email domains, a pending "join request" will be created, which will require an approval from a Workspace Owner or Admin.
> If their email address matches one of your Workspace's allow email domains

"If their email address domain does not match one of your Workspace's allowed domains"

2021-07-02 18:55 UTC, marbemac commented on 6.-migrations/classic.md
> +To start, head over to Stoplight Platform and [create a workspace](https://stoplight.io/welcome/create).
> To start, head over to Stoplight Platform and [create a workspace](https://stoplight.io/welcome/create).

To start, head over to Stoplight Platform and [create a workspace](https://stoplight.io/welcome/create) for your company. Note that while you might have multiple workspaces for your company in Stoplight Classic, you will only have one workspace for your company on the new Stoplight Platform.

---

👆 figured it prob makes sense to call out paradigm shifts for classic users, where we can.

2021-07-02 18:55 UTC, marbemac commented on 6.-migrations/classic.md
> +Wait a few moments for the projects to migrate and you'll see them appear in your left sidebar. Success!
Maybe a note after this that if they re-migrate a project they've already migrated, it will overwrite the existing one?

2021-07-02 19:15 UTC, marbemac approved these changes
👏

2021-07-03 07:54 UTC, philsturgeon approved these changes

2021-07-06 16:18 UTC, merged