Docs/pam 156 mock server update
stoplightio/platform-docs pull request #162
Opened 2021-11-01 21:22 UTC by pamgoodrich

Hi, Nauman. Thanks for your help with this. I organized the content by where and how you use mock servers. Once you approve, I'll update the Mock Servers topic in Studio to (mostly) point to this topic.

My updates:
https://meta.stoplight.io/docs/platform/branches/docs%2Fpam-156-mock-server-update/ZG9jOjIwMTI4MA-working-with-mock-servers

Main:
https://meta.stoplight.io/docs/platform/ZG9jOjIwMTI4MA-working-with-mock-servers

2021-11-02 16:50 UTC, mnaumanali94 requested changes

2021-11-02 16:50 UTC, mnaumanali94 commented on 3.-design/d.setting-up-a-mock-server.md
> +Stoplight mock servers are powered by our [open-source mock server, Prism](https://stoplight.io/open-source/prism).
@pamgoodrich Could be nice to link to how mocks generate data in the Prism documentation.

2021-11-02 16:50 UTC, mnaumanali94 commented on 3.-design/d.setting-up-a-mock-server.md
> +4. Choose a 200 or 400 reponse code, and then choose one of these options:
Response code could be any i.e. 201, 404, e.t.c depending on what's defined in the spec

2021-11-02 16:50 UTC, mnaumanali94 commented on 3.-design/d.setting-up-a-mock-server.md
> +   - Statically generated: Responses are based on the OpenAPI spec.
based on the examples in the OpenAPI spec - to be a little more specific

2021-11-02 16:50 UTC, mnaumanali94 commented on 3.-design/d.setting-up-a-mock-server.md
> +   - Dynamically generated: Responses are generated by Prism.
Probably nice to link to the logic in Prism documentation on how this is generated and how to customize it

2021-11-02 16:50 UTC, mnaumanali94 commented on 3.-design/d.setting-up-a-mock-server.md
> +Swap that URL for your Hosted Prism URL:
They can get the URL from the API overview in docs. Probably nice to point them there.

2021-11-02 16:50 UTC, mnaumanali94 commented on 3.-design/d.setting-up-a-mock-server.md
>  https://workspacename.stoplight.io/mocks/workspacename/todos
This link depends on the project name too

2021-11-02 16:50 UTC, mnaumanali94 commented on 3.-design/d.setting-up-a-mock-server.md
> +## Use Mock Servers with Any HTTP Client
The use case is any HTTP client or within your frontend applications. This URL can be used to safely replace with the API url in prod once its ready. 

This is the most important use case so I would also put this above Studio Desktop

2021-11-02 17:54 UTC, pamgoodrich commented on 3.-design/d.setting-up-a-mock-server.md
> +Stoplight mock servers are powered by our [open-source mock server, Prism](https://stoplight.io/open-source/prism).
Done

2021-11-02 17:58 UTC, pamgoodrich commented on 3.-design/d.setting-up-a-mock-server.md
> +4. Choose a 200 or 400 reponse code, and then choose one of these options:
Fixed

2021-11-02 18:00 UTC, pamgoodrich commented on 3.-design/d.setting-up-a-mock-server.md
> +   - Statically generated: Responses are based on the OpenAPI spec.
Done

2021-11-02 18:06 UTC, pamgoodrich commented on 3.-design/d.setting-up-a-mock-server.md
> +   - Dynamically generated: Responses are generated by Prism.
Done

2021-11-02 18:35 UTC, pamgoodrich commented on 3.-design/d.setting-up-a-mock-server.md
> +Swap that URL for your Hosted Prism URL:
Done

2021-11-02 18:47 UTC, pamgoodrich commented on 3.-design/d.setting-up-a-mock-server.md
> +## Use Mock Servers with Any HTTP Client
Done, I think, but please verify. I moved this to the top with the the three bullets on how to use mock servers.

2021-11-03 14:48 UTC, mnaumanali94 requested changes

2021-11-03 14:48 UTC, mnaumanali94 commented on 3.-design/d.setting-up-a-mock-server.md
> +1. From the documentation for any endpoint in Studio Web.
Should this be bullets instead of numbers? 🤔

2021-11-03 14:48 UTC, mnaumanali94 commented on 3.-design/d.setting-up-a-mock-server.md
> +## Use Mock Servers with Any HTTP Client
I was thinking "Use Mock Servers with Any HTTP Client" should be above " - "Use Mock Servers in Studio Desktop"

2021-11-03 14:48 UTC, mnaumanali94 commented on 3.-design/d.setting-up-a-mock-server.md
> +## Use Mock Servers with Any HTTP Client
These large headings cause them to be hidden on the right TOC

<img width="247" alt="Screenshot 2021-11-03 at 5 48 30 PM" src="https://user-images.githubusercontent.com/17899454/140083199-e787b14a-c7ba-41ef-9415-5d41b442fac7.png">


Can we make them smaller somehow?

2021-11-03 14:50 UTC, mnaumanali94 commented on 3.-design/d.setting-up-a-mock-server.md
> +Swap that URL for your hosted Prism URL:
Can we show the screenshot where it shows "Copy Server URL"

It appears on hover

2021-11-03 15:55 UTC, pamgoodrich commented on 3.-design/d.setting-up-a-mock-server.md
> +## Use Mock Servers with Any HTTP Client
Done

2021-11-03 15:58 UTC, pamgoodrich commented on 3.-design/d.setting-up-a-mock-server.md
> +## Use Mock Servers with Any HTTP Client
I removed the verbs. Now it's just "Studio Web," "Studio Desktop," and "Any HTTP Client."

2021-11-04 14:40 UTC, mnaumanali94 approved these changes
Looks good! Approving but we should probably make all images pop out for consistency. Probably just requires a new line before them

2021-11-04 14:59 UTC, merged