Docs/sydney 170 styleguideupdate
stoplightio/platform-docs pull request #187
Opened 2021-11-20 03:33 UTC by sydstoplight

Overview for Style Guides

2021-11-22 17:43 UTC, pamgoodrich requested changes

2021-11-22 17:43 UTC, pamgoodrich commented on 5.-governance/d.style-guides - copy 2.md
> +Style guides add consistency, reusability, and easy governance to APIs throughout your API program. Tailor the experience for creating style guides in a dedicated project type managed by workspace ow
"...easy governance to APIs throughout..." > "easy governance throughout..."

"...creating style guides in..." > "creating style guides with..." (With sounds better to me. What do you think?)

"Build custom functions..." > "Build custom rules, custom functions..."

2021-11-22 17:43 UTC, pamgoodrich commented on 5.-governance/d.style-guides - copy 2.md
> +* Get API to market faster and better.
API > APIs (?)

2021-11-22 17:43 UTC, pamgoodrich commented on 5.-governance/d.style-guides - copy 2.md
> +Use CI pipelines, such as Spectral-cli and Spectral action, to enforce style guides for different Git repositories.
"CI pipelines" > "Continuous integration (CI) pipelines"

2021-11-22 17:43 UTC, pamgoodrich commented on 5.-governance/d.style-guides - copy.md
> +tags: [Governance]
I understand why you made an extra copy of this topic, but one of the developers also made changes to the original last week, so now we have two different versions of the same topic. I can try to piece them together after we merge, but in general, you should update the existing topics in your branch. Your changes won't impact the published topics until we merge.

2021-11-22 17:43 UTC, pamgoodrich commented on 5.-governance/d.style-guides - copy.md
> +tags: [Governance]
Actually... Is this a copy of the original topic, and you made changes to the original? I'm a little confused. Git will handle versioning for you, so there's no need to create a copy of a topic. We can always roll back to the original version if need be. I may understand your intent here, so let me know.

2021-11-22 17:43 UTC, pamgoodrich commented on 5.-governance/d.style-guides.md
> -Also known as "API Design Guides", "Design Guidelines", "Style Books", or "API Standards", the concept of "make a bunch of decision's and write them down" has helped API teams for decades.
Can you please move the steps for Creating a Style Guide that discuss the new features out of this topic and into d.style-guides - copy 2.md. I'll need to rename that file after we merge, but we don't want to publish that information until SSG is ready for customers. Once we merge, this topic will be published. Clear as mud, I know, but we can go over it in our meeting tomorrow. (For now, move anything related to the new features into this topic: d.style-guides - copy 2.md

2021-11-23 01:20 UTC, sydstoplight commented on 5.-governance/d.style-guides.md
> -Also known as "API Design Guides", "Design Guidelines", "Style Books", or "API Standards", the concept of "make a bunch of decision's and write them down" has helped API teams for decades.
Completed

2021-11-23 01:24 UTC, sydstoplight commented on 5.-governance/d.style-guides - copy.md
> +tags: [Governance]
I created a copy to give me a new page to work rather than changing the original style guide page since this version is completely different. Yes, we can discuss more about the best way to make updates to existing topics.

2021-11-23 01:25 UTC, sydstoplight commented on 5.-governance/d.style-guides - copy 2.md
> +Use CI pipelines, such as Spectral-cli and Spectral action, to enforce style guides for different Git repositories.
Completed

2021-11-23 01:26 UTC, sydstoplight commented on 5.-governance/d.style-guides - copy 2.md
> +* Get API to market faster and better.
I agree, that sounds better. Completed.

2021-11-23 01:27 UTC, sydstoplight commented on 5.-governance/d.style-guides - copy 2.md
> +Style guides add consistency, reusability, and easy governance to APIs throughout your API program. Tailor the experience for creating style guides in a dedicated project type managed by workspace ow
Completed

2021-11-23 22:16 UTC, pamgoodrich approved these changes

2021-11-23 22:19 UTC, merged