Docs/pam 176 rule editor
stoplightio/platform-docs pull request #200
Opened 2021-11-30 21:44 UTC by pamgoodrich

2021-12-02 22:35 UTC, pamgoodrich commented
@naumanali-stoplight : I think I've done enough for early access. We should have pretty good info for people to understand the feature. I highly recommend looking at it in meta:
https://meta.stoplight.io/docs/platform/branches/docs%2Fpam-176-rule-editor/ZG9jOjMwMDI3MjA2-overview

Note that I pulled the examples into their own topic and added some task navigation links to the bottom of each topics. 

It might be good to take a close look at the examples. 
https://meta.stoplight.io/docs/platform/branches/docs%2Fpam-176-rule-editor/ZG9jOjMwNDI1OTM1-rule-examples

I'll stay out of here until I get feedback from you.

Thank you!

2021-12-06 17:36 UTC, mnaumanali94 requested changes

2021-12-06 17:36 UTC, mnaumanali94 commented on 2a.-style-guides/f.refresh-style-guide.md
> +# Refresh Style Guides
I'd use update than refresh across this article

2021-12-06 17:36 UTC, mnaumanali94 commented on 2a.-style-guides/c-create-rules.md
> +
This needs an early access callout

2021-12-06 17:36 UTC, mnaumanali94 commented on 2a.-style-guides/a.style-guide-projects.md
> +> Limited early access content for Shared Style Guides. Shared style guides are available on the **Professional** and **Enterprise** plans for early access participants.
Lets make these callouts warning rather than info.

2021-12-06 17:36 UTC, mnaumanali94 commented
Looks like a great first pass. Lets make these tiny changes and we can get this in.

2021-12-06 17:51 UTC, mnaumanali94 approved these changes

2021-12-06 17:53 UTC, merged