Pam 185 add GitHub workflow to cli
stoplightio/platform-docs pull request #224
Opened 2021-12-28 22:17 UTC by pamgoodrich

Testing/editing on publishing and local projects topics; added Stoplight CLI info; updated screenshots

2021-12-29 17:12 UTC, ryotrellim requested changes
Overall: I think the changes to "Working with Local Projects" are strong, but I believe they would be better served on the "Publishing" page, alongside a few tweaks to how we position that page.

However, I'll defer to @mnaumanali94 as he may have other plans or ideas.

2021-12-29 17:12 UTC, ryotrellim commented on 2.-workspaces/g.automating-publishing.md
I think we should add a *Github Workflow* section here with a brief description, a link to the [Workflow syntax for Github Actions](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions) page, and a link to our workflow. Might be nice to have a screenshot of the workflow as it appears in a PR.

2021-12-29 17:12 UTC, ryotrellim commented on 2.-workspaces/g.automating-publishing.md
>  ## Continuous Integration
This section is specifically about using the Stoplight CLI directly as a means to setting up CI, but the GH Workflow above _also_ facilitates CI. I suggest renaming this to something like *Use Stoplight CLI Directly*.

2022-01-05 21:35 UTC, pamgoodrich commented
@naumanali-stoplight and @ryotrellim : Thanks to both of you for your feedback. I made quite a few changes, mostly by organizing the content as you requested, Nauman (publish by project type). It turned out to be TMI for one topic, in my opinion, so I created a group called "Publishing" under projects, which is where the existing content lives. I can move this to the Documentation area if you think it would be better there. You can see the changes here:

https://meta.stoplight.io/docs/platform/branches/pam-185-add-github-workflow-to-cli/ZG9jOjQ1NTQxNA-publishing-overview

![image](https://user-images.githubusercontent.com/91907863/148292787-c7612c93-601a-415f-af8c-1c68b0a9aa8b.png)

2022-01-06 20:13 UTC, mnaumanali94 requested changes

2022-01-06 20:13 UTC, mnaumanali94 commented on toc.json
> +            "title": "Publishing Overview",
Think this should be just overview

2022-01-06 20:13 UTC, mnaumanali94 commented on toc.json
> +            "title": "Publish Git Projects",
Publish seems redundant in these

2022-01-06 20:13 UTC, mnaumanali94 commented on 2.-workspaces/g.automating-publishing.md
> -> double check your version with the command: `node --version`
Now that its a separate page, I think this callout is redundant here but I can live with it.

2022-01-06 20:13 UTC, mnaumanali94 commented on 2.-workspaces/g.automating-publishing.md
> +* **Git Projects**: Use webhooks to trigger automatic publishing for projects using Git. You can push changes to the default branch set in Stoplight or to any other branch which has publishing enable
I would rather say: Connect your GitHub repository and make updates automatically in Stoplight whenever changes are made within Studio or elsewhere e.g. VS code

2022-01-06 20:13 UTC, mnaumanali94 commented on 2.-workspaces/g.automating-publishing.md
> +* **CLI Projects**: Use the Stoplight CLI to publish local projects, projects that do not use Git, or to facilitate continuous integration. You can also use the Stoplight CLI to automate publishing d
use the Stoplight CLI to automate publishing directly from GitHub. (If you don't want to use the Git integration for some reason)

2022-01-06 20:13 UTC, mnaumanali94 commented on 2.-workspaces/g.automating-publishing.md
> +* **CLI Projects**: Use the Stoplight CLI to publish local projects, projects that do not use Git, or to facilitate continuous integration. You can also use the Stoplight CLI to automate publishing d
Not just GitHub. It could be any Git provider

2022-01-06 20:13 UTC, mnaumanali94 commented on 2.-workspaces/f.working-with-local-projects.md
> +The [GitHub Workflow](https://github.com/stoplightio/stoplight-cli-workflow) uses the Stoplight CLI to automatically publish content when a push is made to .json , .yaml, .yml, or .md file in at leas
Something about it being a Quickstart if you're using GitHub.

2022-01-06 20:52 UTC, pamgoodrich commented on toc.json
> +            "title": "Publishing Overview",
Done

2022-01-06 20:52 UTC, pamgoodrich commented on toc.json
> +            "title": "Publish Git Projects",
Done

2022-01-06 20:58 UTC, pamgoodrich commented on 2.-workspaces/g.automating-publishing.md
> +* **CLI Projects**: Use the Stoplight CLI to publish local projects, projects that do not use Git, or to facilitate continuous integration. You can also use the Stoplight CLI to automate publishing d
Do you want me to remove the bit about local projects and continuous integration? I tried to cover the various use cases. I just added Stoplight CLI Workflow to the last sentence to cover the original intent of this issue. 

Use the Stoplight CLI to publish local projects, projects that do not use Git, or to facilitate continuous integration. You can also use the Stoplight CLI Workflow to automate publishing directly from GitHub.

2022-01-06 21:21 UTC, mnaumanali94 commented on 2.-workspaces/g.automating-publishing.md
> +* **CLI Projects**: Use the Stoplight CLI to publish local projects, projects that do not use Git, or to facilitate continuous integration. You can also use the Stoplight CLI to automate publishing d
Nah I think it is fine. changing it to any git provider and a callout for the better option (Use our integration) should fix it.

2022-01-06 21:34 UTC, pamgoodrich commented on 2.-workspaces/g.automating-publishing.md
> +* **CLI Projects**: Use the Stoplight CLI to publish local projects, projects that do not use Git, or to facilitate continuous integration. You can also use the Stoplight CLI to automate publishing d
Done.

2022-01-06 21:35 UTC, pamgoodrich commented on 2.-workspaces/g.automating-publishing.md
> +1. Navigate to `https://{workspace}.stoplight.io/settings/{project}/automation` in your browser to get the CLI command and token.
See updated changes.

2022-01-06 21:35 UTC, pamgoodrich commented on 2.-workspaces/g.automating-publishing.md
> +* **Stoplight CLI Workflow**: Use the [Stoplight CLI Workflow](https://github.com/stoplightio/stoplight-cli-workflow)  to automatically push data to Stoplight CLI projects from your GitHub repository
done

2022-01-06 21:36 UTC, pamgoodrich commented on 2.-workspaces/g.automating-publishing.md
>  ## Continuous Integration
Done

2022-01-06 21:51 UTC, mnaumanali94 approved these changes

2022-01-06 22:00 UTC, ryotrellim approved these changes
👍

2022-01-06 22:03 UTC, merged