Docs/sydney 190 explorer
stoplightio/platform-docs pull request #227
Opened 2021-12-30 05:22 UTC by sydstoplight

2021-12-30 18:03 UTC, pamgoodrich requested changes
Hi, Sydney. Nice job overall. I left some comments. I did not realize until Troy pointed it out that we have some of this documented here: 

https://meta.stoplight.io/docs/platform/ZG9jOjU4NzU5Ng-exploring-your-api-projects

I'll remove that topic as part of the TOC work, but can you please review it and verify that we have relevant content in your new topics? Thank you!

2021-12-30 18:08 UTC, pamgoodrich commented on 2.-workspaces/m.groups.md
I am not sure why this file is in this branch. It looks like you may have created your branch from something other than main. Remember to always switch to main, pull, and then create your new branch. I will fix the merge conflict on this file after you finish your review updates.

2022-01-02 05:58 UTC, sydstoplight commented on explorer/overview.md
> +
Added a blur to all screenshots for logged in user and project names

2022-01-02 06:00 UTC, sydstoplight commented on explorer/overview.md
> +Poor visibility into available APIs lead to inconsistencies and duplications that suffer costs to your business. Explorer provides visibility by acting as a central repository for all design assets a
Complete

2022-01-02 06:01 UTC, sydstoplight commented on explorer/overview.md
> +After adding projects to your workspace, Explorer analyzes them and creates an indexed, searchable view of your projects.
Complete

2022-01-02 06:03 UTC, sydstoplight commented on explorer/overview.md
> +* Design documents
Complete

2022-01-02 06:06 UTC, sydstoplight commented on explorer/overview.md
> +* Search and Filter
Complete

2022-01-02 06:07 UTC, sydstoplight commented on explorer/overview.md
> +
Complete

2022-01-02 06:08 UTC, sydstoplight commented on explorer/search-and-filter.md
> +API assets compile quickly. With multiple APIs and projects, it becomes difficult to navigate API assets.
Complete

2022-01-02 06:14 UTC, sydstoplight commented on explorer/search-and-filter.md
> +![explore_navigation.png](../assets/images/explore_navigation.png)
Added new image

2022-01-02 06:15 UTC, sydstoplight commented on explorer/view-changelogs.md
> +
Complete

2022-01-02 06:18 UTC, sydstoplight commented on explorer/search-and-filter.md
> +4. Select your desired asset type from the menu.
Complete

2022-01-02 06:19 UTC, sydstoplight commented on explorer/star-repositories.md
> +# Star Repositories
Complete

2022-01-02 06:20 UTC, sydstoplight commented on explorer/star-repositories.md
> +Navigate through hundreds of assets in your project by starring what you need.
Complete

2022-01-02 06:40 UTC, sydstoplight commented on explorer/star-repositories.md
> +Stars in Explorer operate like bookmarks. You can star assets within your workspace, docs, endpoints, or models in order to easily revisit them.
Complete

2022-01-02 06:41 UTC, sydstoplight commented on explorer/track-dependencies.md
> +1. Log in to your workspace, and then select **Explore** on the left pane. Select your desired endpoint or model.
Complete

2022-01-02 06:41 UTC, sydstoplight commented on explorer/track-dependencies.md
> +Overlapping references to models used in multiple endpoints often breaks changes before detection.
Complete

2022-01-02 07:13 UTC, sydstoplight commented on 2.-workspaces/m.groups.md
Complete

2022-01-04 22:00 UTC, pamgoodrich approved these changes

2022-01-04 22:01 UTC, merged