Pam=268 file upload and media types
stoplightio/platform-docs pull request #320
Opened 2022-04-05 21:24 UTC by pamgoodrich

This request is pretty specific, but also useful for customers, I think. I created a "Work with Media Types" topic that we can hopefully build on over time, and if you have suggestions, I can add more types now to help make this topic more useful.

If you think I should stick to a "Work with File Uploads" topic, I can do that too. Let me know and happy to meet by phone for a few minutes if that helps.

2022-04-06 13:57 UTC, daniel-white requested changes
some small nits, some bigger things we should discuss

2022-04-12 20:22 UTC, pamgoodrich commented on toc.json
> +                "title":"Work with Content Types",
Changed to Media Types in the TOC so it matches the topic.

2022-04-12 20:23 UTC, pamgoodrich commented on 3.-design/work-with-content-types.md
> +Use the multiform/form-data media type to upload files with request content for POST, PUT, and PATCH operations.
Ugh. Sorry about that. Fixed.

2022-04-12 20:24 UTC, pamgoodrich commented on 3.-design/work-with-content-types.md
> +From published documentation, you can send a request to a live server or a mock server. Mock servers currently do not return valid requests for multiform/form-data media types, however.
Done

2022-04-12 20:29 UTC, pamgoodrich commented
Rendered version: https://meta.stoplight.io/docs/platform/branches/pam%3D268-file-upload-and-media-types/c2f20944173d7-work-with-media-types

2022-04-22 15:14 UTC, daniel-white commented on 3.-design/work-with-content-types.md
> +You can add multiple media types to request and response bodies as needed. The following example shows a request body with three media types: application/json, application/pdf, and text/html.
```suggestion
Within a single operation, you can add multiple media types to request and response bodies as needed. Each media type indicates that the body contains appropriate content.  The following example shows a request body with three media types: `application/json`, `application/pdf`, and `text/html`. This indicates that the operation accepts one a JSON document, a PDF file or a HTML document.
```

2022-04-22 15:19 UTC, daniel-white commented on 3.-design/work-with-content-types.md
> +[Media types](https://spec.openapis.org/oas/v3.1.0#media-types) are a format of a request or response body data. Each media type includes a schema that indicates the type of data and properties.
```suggestion
[Media types](https://spec.openapis.org/oas/v3.1.0#media-types) declare the format of a request or response body content. For instance: 
- An endpoint on the server allow accepting PDF files with `application/pdf`, for a file upload
- An endpoint may return a PNG image with `image/png` for display on a web page
- A client and server may exchange messages with `application/json` or `application/xml`
```

2022-04-22 15:20 UTC, daniel-white commented on 3.-design/work-with-content-types.md
> +Here is the JSON for this example:
```suggestion
Here is a snippet of an Open API spec in JSON for this example:
```

2022-04-22 15:21 UTC, daniel-white commented on 3.-design/work-with-content-types.md
> +## Multipart/form-data
```suggestion
## Working with multipart and form requests
```

2022-04-22 15:24 UTC, daniel-white commented on 3.-design/work-with-content-types.md
> +If a format you need is not listed, you can manually add it to the list.
```suggestion
If a media type you need is not listed, you can manually add it to the list.
```

2022-04-22 20:07 UTC, daniel-white commented on 3.-design/work-with-content-types.md
> +Within a single operation, you can add multiple media types to request and response bodies as needed. Each media type indicates that the body contains appropriate content. The following example shows
```suggestion
Within a single operation, you can add multiple media types to request and response bodies as needed. Each media type indicates that the body contains appropriate content. The following example shows a request body with three media types: `application/json`, `application/pdf`, and `text/html`. This indicates that the operation accepts either a JSON document, a PDF file or a HTML document in a single request.
```

2022-04-22 20:49 UTC, pamgoodrich commented on 3.-design/work-with-content-types.md
> +Within a single operation, you can add multiple media types to request and response bodies as needed. Each media type indicates that the body contains appropriate content. The following example shows
Last comment added.

2022-04-26 14:10 UTC, mnaumanali94 approved these changes

2022-04-26 14:10 UTC, mnaumanali94 commented on 3.-design/work-with-content-types.md
> +## Work with Multipart abd Form Requests
```suggestion
## Work with Multipart and Form Requests
```

2022-04-26 14:10 UTC, mnaumanali94 commented on 3.-design/work-with-content-types.md
> +            },
```suggestion
            }
```

2022-04-26 17:26 UTC, daniel-white approved these changes

2022-04-26 17:32 UTC, merged