Updates based on feedback
stoplightio/platform-docs pull request #410
Opened 2022-06-07 18:59 UTC by pamgoodrich

Clarified that stable IDs are in API and markdown files. Added guidelines for using slugs.

2022-06-16 01:39 UTC, marbemac requested changes

2022-06-16 01:39 UTC, marbemac commented on 4.-documentation/stoplight-urls.md
> +* `https://meta.stoplight.io/docs` is the workspace URL or custom domain, along with the folder location of published documentation.
`https://meta.stoplight.io/docs` is the workspace URL or custom domain, along with the `/docs` prefix which is present for all project documentation.

(kind of a nit, but the word "folder" kind of confused it a bit for me?)

2022-06-16 01:39 UTC, marbemac commented on 4.-documentation/stoplight-urls.md
> +* `platform` is the name of the project in slug format.
Something along lines of the below maybe?

`platform` is the the project's `slug` value. This value can be changed in your project settings.

2022-06-16 01:39 UTC, marbemac commented on 4.-documentation/stoplight-urls.md
> +* For API files, published URLs for endpoints and models have different stable IDs. The root-level stable ID is used to generate the child stable IDs, however.
Hmm - how many folks have asked about this specific question. Just not sure if this sentence will confuse more readers than it helps 🤔.

2022-06-16 13:57 UTC, pamgoodrich commented on 4.-documentation/stoplight-urls.md
> +* For API files, published URLs for endpoints and models have different stable IDs. The root-level stable ID is used to generate the child stable IDs, however.
We've had (I think) 3 customers ask how the API URLs are constructed.

2022-06-16 13:58 UTC, pamgoodrich commented on 4.-documentation/stoplight-urls.md
> +The endpoin
Oops! Thank you.

2022-06-16 14:21 UTC, pamgoodrich commented on 4.-documentation/stoplight-urls.md
> +* For API files, published URLs for endpoints and models have different stable IDs. The root-level stable ID is used to generate the child stable IDs, however.
I removed this sentence:

The root-level stable ID is used to generate the child stable IDs, however.

2022-06-23 19:42 UTC, marbemac approved these changes

2022-06-23 20:11 UTC, merged