Update guest visibility access for internal items
stoplightio/platform-docs pull request #426
Opened 2022-06-16 21:39 UTC by heitortsergent

Closes #417.

2022-06-16 21:40 UTC, heitortsergent commented on 4.-documentation/set-internal-docs.md
> +You can prevent articles, paths, and models from being visible to **guest users** and **users who are not members of a workspace**.
What's the difference between "external users" and "users who are not members of a workspace" like it was written before?

2022-06-16 21:42 UTC, heitortsergent commented
I tried making small changes to the current files we have, I'm not sure if we want to be more descriptive about this restriction.

2022-06-21 14:12 UTC, pamgoodrich commented on 4.-documentation/set-internal-docs.md
> +You can prevent articles, paths, and models from being visible to **guest users** and **users who are not members of a workspace**.
External users are members of a workspace; they just have limited access. If your project has public visibility, you can view it without being a member of a workspace. Our meta docs are an example of this.

2022-06-21 17:01 UTC, pamgoodrich requested changes

2022-06-21 17:16 UTC, heitortsergent commented on 2.-workspaces/l.project-roles.md
> +**Guest**: Can view public documentation in published branches once they've been invited. You cannot assign the guest role; it is automatically assigned when guests are invited to a project.
@pamgoodrich and I can make the same update here as the other comment.

2022-06-21 17:32 UTC, pamgoodrich requested changes

2022-06-21 17:32 UTC, pamgoodrich commented on 2.-workspaces/k.workspace-roles.md
> +**Guests**: Restricted to viewing public documentation for projects that they are granted explicit access to. Guests are users outside your company or organization, such as partners who require authe
I like that. Maybe instead of saying "items marked as internal," we can say "articles, API paths, and models marked as internal."

2022-06-21 17:32 UTC, pamgoodrich commented on 2.-workspaces/l.project-roles.md
> +**Guest**: Can view public documentation in published branches once they've been invited. You cannot assign the guest role; it is automatically assigned when guests are invited to a project.
That works

2022-06-22 15:46 UTC, pamgoodrich approved these changes

2022-06-22 15:46 UTC, pamgoodrich commented on 2.-workspaces/k.workspace-roles.md
Nice job!

2022-06-23 20:37 UTC, heitortsergent commented on 4.-documentation/set-internal-docs.md
> +
@ryotrellim would you be able to help me add an example here for why marking an API path or model as internal would be useful?

I was thinking of adding something like:

"A development team is working on a new endpoint, and you don't want to have that endpoint visible to yours users before it's available in production."

2022-06-23 20:38 UTC, heitortsergent commented
@pamgoodrich after looking at this again, would it make sense to move this out of the "Documentation" section, and instead move it under "Project Sidebar" since it now covers both articles and API paths and models?

2022-06-23 20:47 UTC, pamgoodrich commented
I think it's worth keeping on its own. Making something internal doesn't just impact the TOC. It also impacts search. It basically hides the content from users, not just the navigation 9which is the project sidebar).

2022-07-01 16:07 UTC, ryotrellim commented on 4.-documentation/set-internal-docs.md
> +
The sentence you wrote is probably a good reason to use unlisted branches/versions rather than internal. I recommend:

- An API operation on an otherwise publicly-available API is only intended for internal use.
- A project or a repository contain a mix of public and internal APIs and you want to keep the documentation together in the same project.

2022-07-01 20:34 UTC, merged