Pam 423 validation list change
stoplightio/platform-docs pull request #488
Opened 2022-08-11 19:46 UTC by pamgoodrich

## Motivation and Context

#InsertIssueNumberHere

## Description

## How Has This Been Tested?

## Screenshot(s)/recordings(s)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] This PR's code follows as closely as possible [the coding style/guidelines of this project](???).
- [ ] I have added error reporting and followed [the error reporting guidelines](???).
- [ ] I have added event tracking and followed [the event tracking guidelines](???).
- [ ] I have updated any relevant documentation accordingly to reflect this PR's changes.
- [ ] I have added automated tests (unit/integration/e2e/other) to cover my changes.
- [ ] All new and existing tests pass locally (excluding flaky CI tests).

2022-08-18 17:49 UTC, lanemc requested changes

2022-08-18 17:49 UTC, lanemc commented on 2a.-style-guides/c-create-rules.md
> +   Options are error, warning, information, and hint. When applied to an API project, the severity levels appear in the **API Design Checker** editor. You can also choose to disable a rule.
error, warning, hint, message

2022-08-18 17:49 UTC, lanemc commented on 2a.-style-guides/style-guide-quick-start.md
> +2. Notice that your API is automatically validated against the Stoplight rules.
Could say validated against Stoplight Spectral linter rules, as a branding op

2022-08-18 17:49 UTC, lanemc commented on 3.-design/validation-and-linting.md
> +Depending on the ruleset, the **API Design Checker** can show errors, warnings, informational messages, and hints.
Swap the order of 'hints' and 'messages' since that's how we are ordering severity

2022-08-18 17:53 UTC, pamgoodrich commented on 2a.-style-guides/c-create-rules.md
> +   Options are error, warning, information, and hint. When applied to an API project, the severity levels appear in the **API Design Checker** editor. You can also choose to disable a rule.
Interesting... we have a discrepency between what the Validation UI shows and what you can select in style guides. This doc is for creating rules, and the list is:

![image](https://user-images.githubusercontent.com/91907863/185461936-1e057326-952e-4794-a374-8e72c8837584.png)

@naumanali-stoplight : We should probably make these consistent.

2022-08-18 18:04 UTC, mnaumanali94 commented on 2a.-style-guides/c-create-rules.md
> +   Options are error, warning, information, and hint. When applied to an API project, the severity levels appear in the **API Design Checker** editor. You can also choose to disable a rule.
Hmmm... IMO we should use what spectral has: https://meta.stoplight.io/docs/spectral/e5b9616d6d50c-custom-rulesets#severity

Error, Warning, Info(rmation) and Hint

2022-08-18 18:08 UTC, pamgoodrich commented on 2a.-style-guides/style-guide-quick-start.md
> +2. Notice that your API is automatically validated against the Stoplight rules.
So we validate against whatever style guide you have enabled. It's a bit tricky. Spectral "powers" the linting, but the actual validation depends on whatever style guide you've chosen to enable.

2022-08-18 22:04 UTC, heitortsergent approved these changes

2022-08-18 22:04 UTC, heitortsergent commented on 3.-design/validation-and-linting.md
> +Validation rules signify whether your OpenAPI descriptions and generic JSON/YAML are valid. An example OAS validation rule is one that requires a unique `operationId` for every operation.
I think we could keep `API descriptions` instead of `OpenAPI descriptions` here? It's still accurate, and will be accurate once we add support for other types of API descriptions.

2022-08-19 13:47 UTC, pamgoodrich commented on 2a.-style-guides/b-create-targets.md
> +Targets, referred to as aliases in [Spectral](https://meta.stoplight.io/docs/spectral/674b27b261c3c-overview), reference commonly used areas of API specification documents, such as OpenAPI or AsyncAP
Good suggestion! Thank you!

2022-08-19 13:48 UTC, pamgoodrich commented on 3.-design/validation-and-linting.md
> +Validation rules signify whether your OpenAPI descriptions and generic JSON/YAML are valid. An example OAS validation rule is one that requires a unique `operationId` for every operation.
Done

2022-08-19 13:51 UTC, pamgoodrich commented on 2a.-style-guides/c-create-rules.md
> +   Options are error, warning, information, and hint. When applied to an API project, the severity levels appear in the **API Design Checker** editor. You can also choose to disable a rule.
Followed Spectral and SSG naming standards

2022-08-19 13:51 UTC, pamgoodrich commented on 3.-design/validation-and-linting.md
> +Depending on the ruleset, the **API Design Checker** can show errors, warnings, informational messages, and hints.
Followed Spectral order

2022-08-19 13:52 UTC, pamgoodrich commented on 2a.-style-guides/style-guide-quick-start.md
> +2. Notice that your API is automatically validated against the Stoplight rules.
Change not made.

2022-08-22 14:08 UTC, lanemc approved these changes
LGTM!

2022-08-22 14:11 UTC, merged