Image Hosting for Private Repos
stoplightio/platform-docs pull request #557
Opened 2022-10-11 18:30 UTC by heitortsergent

Closes #509.

- [x] Add images to web projects via + -> Add image
- [x] File size limit

2022-10-13 21:08 UTC, pamgoodrich requested changes
I asked a couple of questions about access because we seem to have conflicting guidance.

2022-10-13 21:08 UTC, pamgoodrich commented on 4.-documentation/f.adding-images.md
> +The image URL has the same visibility as the Stoplight project visibility, so images uploaded to a public project will be visible by anyone who has access to the image URL, while images uploaded to i
I thought someone said that project visibility didn't impact image visibility. Did that get fixed?

2022-10-13 21:08 UTC, pamgoodrich commented on 4.-documentation/f.adding-images.md
> +For private Git repositories that are connected to a public Stoplight project, Stoplight will display a public copy of any images in the repository that are included in a Markdown article or API docu
Oh this is what I was thinking of. So if you have a private Git repo and an internal project, your images are not public, correct? The first paragraph sounds like that's the case.

2022-10-13 21:08 UTC, pamgoodrich commented on 4.-documentation/f.adding-images.md
> +If you have an image in a Git repository that's larger than 15mb, that image will not be displayed in your Stoplight project.
15mb > 15 MB

https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/bits-bytes-terms

2022-10-13 21:11 UTC, heitortsergent commented on 4.-documentation/f.adding-images.md
> +The image URL has the same visibility as the Stoplight project visibility, so images uploaded to a public project will be visible by anyone who has access to the image URL, while images uploaded to i
Yeah, I think I said that to you. Then I tested it and found out drag-and-drop does actually follow project permissions. :D

2022-10-13 21:11 UTC, heitortsergent commented on 4.-documentation/f.adding-images.md
> +For private Git repositories that are connected to a public Stoplight project, Stoplight will display a public copy of any images in the repository that are included in a Markdown article or API docu
Yep, that's correct.

2022-10-14 19:14 UTC, heitortsergent commented on 4.-documentation/f.adding-images.md
> +If you have an image in a Git repository that's larger than 15mb, that image will not be displayed in your Stoplight project.
Fixed it, thanks!

2022-10-14 19:30 UTC, pamgoodrich approved these changes

2022-10-19 14:48 UTC, merged